theme: jekyll-theme-cayman
title: Benchmarking predictive frameworks of civil war onset
description: Julie Kloeckner, Neil Scheidwasser, Victor Stimpfling
markdown: kramdown
github:
  repository_url: https://github.com/epfl-ada/ada-2020-project-milestone-p3-p3_navaja
